/*
This function authentication ......

Author: ....
Date: ...
Reviewed by: ....
Review date: ...
Approved by: ....
Approve date: ....
Version: ....

Parameters: $userId - string user's ID
            $userSecret = string user's secret

Returns: $obj(
              valid-> true | false
              token-> string of token
              expiry-> timestamp of expiry)

Usage: $res=validateAuthen($useId, $userSecret);
        .....

*/
function validateAuthen($userId, $userSecret)
  {
  /*
  Codes to get authentication, etc...
  Then create $res accordingly...
  */
  return ($res);
  }
